apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: dodo-payments
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "dododb"
  REACT_APP_API_URL: "http://backend-service:3000"