apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: dodo-payments
type: Opaque
stringData:
  DB_USER: dodoadmin
  DB_PASSWORD: dodopassword123
  POSTGRES_DB: dododb
  POSTGRES_USER: dodoadmin
  POSTGRES_PASSWORD: dodopassword123