---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: dodo-payments
type: Opaque
stringData:
  DB_USER: "${DB_USER}"
  DB_PASSWORD: "${DB_PASSWORD}"
  POSTGRES_DB: "${POSTGRES_DB}"
  POSTGRES_USER: "${DB_USER}"
  POSTGRES_PASSWORD: "${DB_PASSWORD}"
