apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dodo-payments
  namespace: argocd
  labels:
    app: dodo-payments
    environment: dev
spec:
  project: default

  source:
    repoURL: https://github.com/Ravi-Chandran-B/dodo-payments-devops-assignment.git
    targetRevision: main
    path: task1-kubernetes/manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: dodo-payments

  syncPolicy:
    automated:
      prune: true      
      selfHeal: true   
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas